#!/bin/bash
echo "TELEGRAM_ID = $TG_TELEGRAM_ID
ENABLE_PROXY = $TG_ENABLE_PROXY
PROXY_URL = \"$TG_PROXY_URL\"
GROUP_TOKEN = \"$TG_GROUP_TOKEN\"
FRIEND_TOKEN = \"$TG_FRIEND_TOKEN\"
ACCESS_TOKEN = \"$QQ_ACCESS_TOKEN\"
SECRET = \"$QQ_SECRET\"
API_ROOT = \"$QQ_API_ROOT\"
POST_HOST = \"$QQ_POST_HOST\"
POST_PORT = $QQ_POST_PORT" > forward-bot/constant.py

python3 forward-bot/main.py
